version: "3.9"
services:
  mysql8:
    image: mysql:5.7
    container_name: mysql5.7
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: true
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  postgres13:
    image: postgres:13
    container_name: postgres13
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  unleash:
    image: unleashorg/unleash-server
    container_name: unleash
    restart: always
    ports:
      - "4242:4242"
    environment:
      DATABASE_HOST: postgres13
      DATABASE_NAME: test
      DATABASE_USERNAME: test
      DATABASE_PASSWORD: test
      DATABASE_SSL: false
    depends_on:
      - postgres13

volumes:
  mysql-data:
  postgres-data:
